[param]
interface_type = "Uart"
comport_uart = "/dev/ttyUSB0"
speed_uart = "2000000"
speed_jlink = "1000"
bl60x_brd = "IoTKitA"
bl60x_xtal = "40M"
chip_flash_type = "GD25Q16E"
verify = "True"
aes_key = ""
aes_iv = ""
addr = "0x0"

[check_box]
partition_download = true
boot2_download = true
bin_download = true
media_download = false
use_romfs = false
mfg_download = false
ro_params_download = true
ckb_erase_all = false
encrypt = false
download_single = false

[input_path]
pt_bin_input = "/home/rjwang/work/bl_iot_sdk/tools/flash_tool/bl602/partition/partition_cfg_2M.toml"
boot2_bin_input = "/home/rjwang/work/bl_iot_sdk/tools/flash_tool/img/blsp_boot2_PLL.bin"
cfg2_bin_input = "/home/rjwang/work/bl_iot_sdk/customer_app/sdk_app_ble_sync/build_out/sdk_app_ble_sync.bin"
meida_bin_input = ""
romfs_dir_input = ""
mfg_bin_input = ""
img_bin_input = ""
